### ISSUE TITLE
過去をさかのぼろうとすると表示順序がおかしい。

### ISSUE THREAD

**Issue by rbtnn** [akechi/project-l#10]
以下のように上にスクロールしていって過去をさかのぼろうとすると、日付を無視して時間のみでソートされているっぽいです。
原因はわかりませんがよろしくお願いします。

**過去をさかのぼろうとする前**
![2015-08-29 04 12 47](https://cloud.githubusercontent.com/assets/1595779/9560460/09fbebca-4e50-11e5-83d6-27a7bea4a4fd.png)

**過去をさかのぼろうとする後**
![2015-08-29 04 12 38](https://cloud.githubusercontent.com/assets/1595779/9560459/0873ad10-4e50-11e5-8a9a-18c75ff5c525.png)

**Comment by kamichidu** [comment]
oh... 内部的に、重複排除の目的で各メッセージにつけられたidで表示とか並び順を制御しているんですが、日付見ないとダメですね...

**Comment by kamichidu** [comment]
対応しました。
