### ISSUE TITLE
キーボード出現時の発言ログ

### ISSUE THREAD

**Issue by crazymaster** [akechi/project-l#2]
テキスト入力エリアをタップするとキーボードが現れるのですが、
発言ログを最新の発言までスクロールしてある場合においても
キーボードが現れる前の状態に発言ログが固定されたままです。
（つまり最新の発言がキーボードで隠れてしまいます。）

発言ログを最新の発言までスクロールしてある場合では
キーボードが現れると発言ログはそのまま上にスライドされると良いと思います。

**Comment by kamichidu** [comment]
最新版で対応しました。

**Comment by crazymaster** [comment]
最新の発言までスクロールしてある場合の挙動は直ったのですが、
していない場合に固定されなくなってしまいました。

**Comment by kamichidu** [comment]
挙動的に、今は以下を意図しています。
1. 最新のメッセージが表示されていたら、自動スクロールで追従
2. 最新のメッセージが表示されていないなら、過去ログを読んでいる状態と仮定して自動スクロールしない

そして現状、画像のインライン展開が行われるときに、スクロール量の調整が不十分です。
これ、動き的にどうするのが直感的なのか悩んでます。
