### ISSUE TITLE
ヘッダの通常非表示化

### ISSUE THREAD

**Issue by hokorobi** [akechi/project-l#4]
表示領域確保のため、通常時はヘッダ（メニュー？）が非表示になっているとありがたいです。

**Comment by crazymaster** [comment]
非表示化はともかく、ToolBar(ActionBar)にアプリ名ではなく部屋の名前を表示してもいいかもしれませんね。

**Comment by kamichidu** [comment]
設定として、以下を追加しました。
1. 今のまま
2. 部屋名表示
3. 非表示

**Comment by hokorobi** [comment]
ありがとうございます、非表示に出来ました。
非表示に設定した後に、設定を変える場合は、どのように操作したら良いでしょう？

**Comment by kamichidu** [comment]
ハードウェアボタン (物理ボタン) でメニューが開くと思うので、Settingsから再度設定変更お願いします。

ハードウェアボタンがない機種の場合は、どうしよう....
一応この場合も、アプリケーションデータの削除でデフォルトに戻ります。

**Comment by hokorobi** [comment]
ありがとうございます、ハードウェアボタンがない機種でした。

> ハードウェアボタンがない機種の場合は、どうしよう....
> 部屋の選択の最下段などに出す感じが良いでしょうか？
