### ISSUE TITLE
起動時の通知について

### ISSUE THREAD

**Issue by crazymaster** [akechi/project-l#5]
アプリ起動時に通知されるのは煩わしい気がしますね。
ステータス表示（バックグラウンドで動いているか否か）なら別なのですが...

**Comment by kamichidu** [comment]
バックグラウンドで常にイベント待ちしているので、ステータス表示したほうがいいかな?という気がしてます。
ただ煩わしいのは確かなので、消すかな...

**Comment by kamichidu** [comment]
最新版で消しました。
