### ISSUE TITLE
過去ログから最新の発言へスクロール

### ISSUE THREAD

**Issue by hokorobi** [akechi/project-l#6]
過去ログを読んでいて、最新の発言まで戻る（一気に一番下までスクロール）といった操作が簡単に出来ると良いかと思います。

**Comment by kamichidu** [comment]
暫定版で、スクロール中にショートカットボタンを表示するようにしてみました。
これから色々と調整は必要ですが、こんな感じで使い勝手どうでしょう？

**Comment by hokorobi** [comment]
想像していた感じです！
ありがとうございます。
だいぶストレスが減りました。

必要な「調整」の中に含まれているかもしれませが、以下の様なことを感じました。
- 最下段移動のボタンが表示されにくい
- スクロールの加速度？　が小さい場合にはボタンは非表示にしたい
- スクロール方向のみのボタンを表示したい

**Comment by kamichidu** [comment]
はい、それらを調整する予定ですね。
アイコンどうしようか、とかもありつつ。

**Comment by kamichidu** [comment]
調整入れてみたので、最新版で試していただけますか？

**Comment by hokorobi** [comment]
ありがとうございます、良さ気です。

**Comment by kamichidu** [comment]
ありがとうございます。
アイコンはそのうち変えますが、機能自体はこれでfixということにします。

何か問題あれば、reopenかissueを立てて頂ければ助かります。

**Comment by hokorobi** [comment]
了解しました。
