### ISSUE TITLE
Feature request: 画像のインライン展開

### ISSUE THREAD

**Issue by crazymaster** [akechi/project-l#7]

**Comment by kamichidu** [comment]
データ通信量の兼ね合いもあるので、設定で切り替えられる方向で考えてみます。
wifiならインライン展開有効、とかもあれば便利かも。

**Comment by kamichidu** [comment]
最新版で実装しました。
デフォルト無効になっているので、設定から有効化お願いします。

**Comment by kamichidu** [comment]
通信は特に気にならなかったため、デフォルトでwifi時にのみ有効としました。お試しください。

**Comment by crazymaster** [comment]
試して見たけど良さげでした。
