### ISSUE TITLE
Reloadが欲しい。

### ISSUE THREAD

**Issue by rbtnn** [akechi/project-l#8]
現状、発言後にリロードがかからないので、リロードしようかと思ったのですがそういった機能が見つかりませんでした。
なので、リロード出来る機能か、もしくは発言後自動的にリロードしてくれるといいなとおもいました。

よろしくお願いいたします。

**Comment by kamichidu** [comment]
現状、発言後のリロードは行われるようになっていますが、lingrの取得漏れの可能性が高いです。
自動的にリロードはネットワーク接続の頻度が上がるため、ボタンを設置する方向で考えます。

**Comment by rbtnn** [comment]
了解です。

**Comment by kamichidu** [comment]
追加しました。
最新版で試してみてください。
